require: rubocop-bridgetown

inherit_gem:
  rubocop-bridgetown: .rubocop.yml

AllCops:
  TargetRubyVersion: 3.1

  Exclude:
    - .gitignore
    - .rubocop.yml
    - "*.gemspec"

    - Gemfile.lock
    - CHANGELOG.md
    - LICENSE.txt
    - README.md
    - Rakefile
    - bridgetown.automation.rb

    - script/**/*
    - test/fixtures/**/*
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - lib/tasks/*.rake

Metrics/ParameterLists:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - lib/tasks/*.rake
